### PR TITLE
Add MacOS support

### PR DESCRIPTION
**Pull request by dm4web**
I`m tested macOS builds (cli and gui) and it`s perfect working on MacBook M2 Pro 14 12CPU/19GPU (Apple Silicon).
image

### CODE REVIEW

**Comment by RainbowCookie32** [comment]
Hi, thanks for the PR! Changes look good to me, but I don't have any Apple devices, so I'm fine with merging this as long as you are fine with me knocking at your door if someone comes knocking at mine with a macOS-specific issue 😅

**Comment by dm4web** [comment]
> Hi, thanks for the PR! Changes look good to me, but I don't have any Apple devices, so I'm fine with merging this as long as you are fine with me knocking at your door if someone comes knocking at mine with a macOS-specific issue 😅

No problem, I think the only problem might be preventing it from running from macOS, but usually just requires permission in the privacy settings like other unsigned programs. This is the standard way to run such programs. You can either put it in the README, or just count on macOS users to know about it. Either way, I'm willing to help with any difficulties on macOS (as much as I can).

**Comment by RainbowCookie32** [comment]
We can add it to the README later if people start showing up with the issue I guess, I'll merge then. Thanks!

**Comment by LuckyiXI** [comment]
Could i get some help on this? i downloaded the mac zip egui but it appears as a executable in my downloads

**Comment by dm4web** [comment]
> Could i get some help on this? i downloaded the mac zip egui but it appears as a executable in my downloads

This is normal. Building in this library into a full-fledged application is impossible. (Or I just don't know about it). So just go to the console and run the ./binary executable in the folder where it resides.

**Comment by LuckyiXI** [comment]
what folder exactly? here are pics of what im seeing

Screenshot 2024-12-26 at 6 24 15 PM
Screenshot 2024-12-26 at 6 21 57 PM

**Comment by LuckyiXI** [comment]
Screenshot 2024-12-27 at 12 18 27 AM

**Comment by dm4web** [comment]
I mean Intel CPUs not supported by this pipelines. Please, create issue.

**Pull request merged**
